package net.fhirfactory.dricats.model.topology.reference.common.valuesets;

public enum ElementTypeEnum {
    APPLICATION_COLLABORATION,
    APPLICATION_COMPONENT,
    APPLICATION_DATA_OBJECT,
    APPLICATION_SERVICE,
    APPLICATION_FUNCTION,
    APPLICATION_INTERFACE,
    APPLICATION_PROCESS,
    APPLICATION_INTERACTION,
    APPLICATION_EVENT,
    ARTIFACT,
    COMMUNICATION_NETWORK,
    DEVICE,
    DISTRIBUTION_NETWORK,
    EQUIPMENT,
    FACILITY,
    MATERIAL,
    NODE,
    PATH,
    SYSTEM_SOFTWARE,
    TECHNOLOGY_INTERFACE,
    TECHNOLOGY_COLLABORATION,
    TECHNOLOGY_FUNCTION,
    TECHNOLOGY_INTERACTION,
    TECHNOLOGY_PROCESS,
    TECHNOLOGY_SERVICE
}
