<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.fhirfactory.dricats</groupId>
        <artifactId>dricats-middleware-oam-ui</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>dricats-middleware-oam-ui-testpm</artifactId>
    <name>DRICaTS :: Middleware :: OAM :: UI :: Test Presentation Manager (BEFE)</name>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>

        <!-- DRICaTS Core Model -->

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Apache Camel -->

        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-netty-http</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-openapi-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-main</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-direct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-bean</artifactId>
        </dependency>

        <!--*******************************************************************************-->
        <!-- Logging (SLF4J) Libraries                                                     -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.jboss.logging</groupId>
            <artifactId>jboss-logging</artifactId>
            <version>3.5.0.Final</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-configuration</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-middleware-configserver</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <id>run-uitest</id>
                        <goals>
                            <goal>java</goal>
                        </goals>
                        <configuration>
                            <skip>false</skip>
                            <mainClass>net.fhirfactory.dricats.middleware.oam.uitest.UitestApplication</mainClass>
                            <classpathScope>runtime</classpathScope>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <!-- Build a WildFly Bootable JAR to run with an embedded WildFly instance -->
            <plugin>
                <groupId>org.wildfly.plugins</groupId>
                <artifactId>wildfly-jar-maven-plugin</artifactId>
                <version>12.0.0.Final</version>
                <configuration>
                    <feature-packs>
                        <feature-pack>
                                <location>wildfly@maven(org.jboss.universe:${version-org.wildfly})</location>
                        </feature-pack>
                    </feature-packs>
                    <layers>
                        <layer>ee-core-profile-server</layer>
                        <!--layer>cdi</layer-->
                        <!--layer>ee-integration</layer-->
                        <!--layer>elytron</layer-->
                        <!--layer>jaxrs</layer-->
                        <!--layer>undertow</layer-->
                        <layer>logging</layer>
                        <!--layer>jsonp</layer-->
                        <!--layer>jsonb</layer-->
                    </layers>
                    <cli-sessions>
                        <cli-session>
                            <script-files>
                                <script>src/main/scripts/logging.cli</script>
                            </script-files>
                            <properties-file>src/main/scripts/cli.properties</properties-file>
                            <resolve-expressions>true</resolve-expressions>
                        </cli-session>
                    </cli-sessions>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>bootable-jar</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.wildfly.plugins</groupId>
                        <artifactId>wildfly-jar-maven-plugin</artifactId>
                        <configuration>
                            <!--hollow>true</hollow-->
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>package</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
