<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.fhirfactory.dricats</groupId>
        <artifactId>dricats-model</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>dricats-model-core</artifactId>
    <name>DRICaTS :: Data Models :: Core</name>
    <packaging>jar</packaging>

    <properties>
   </properties>

    <dependencies>

        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <version>${version-jakarta.ra-api}</version>
            <scope>provided</scope>
        </dependency>
    	<!--
        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-resources</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        -->

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-constants</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <dependency>
	        <groupId>net.fhirfactory.dricats</groupId>
	        <artifactId>dricats-common</artifactId>
	        <version>${project.version}</version>
        </dependency>
        
        <!--*******************************************************************************-->
        <!-- Apache Commons Libraries                                                      -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${version-org.apache.commons-lang3}</version>
        </dependency>
        
        <!--*******************************************************************************-->
        <!-- JSON Manipulation Libraries                                                   -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <scope>compile</scope>
            <version>${version-org.json}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${version-com.fasterxml.jackson.core-jackson-core}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <version>${version-com.fasterxml.jackson.datatype-jackson-datatype-jsr310}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${version-com.fasterxml.jackson.core-jackson-databind}</version>
        </dependency>
        
        <!--*******************************************************************************-->
        <!-- Logging (SLF4J) Libraries                                                     -->
        <!--*******************************************************************************-->
        
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <scope>compile</scope>
        </dependency>
        
        <!--*******************************************************************************-->
        <!-- Junit5 (tests)                                                               -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>