<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.fhirfactory.dricats</groupId>
        <artifactId>dricats-middleware-messagegrid</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>dricats-middleware-messagegrid-satellite</artifactId>
    <name>DRICaTS :: Middleware :: MessageGrid :: Satellite </name>
    <packaging>jar</packaging>

    <properties>

    </properties>

    <dependencies>

        <!--*******************************************************************************-->
        <!-- JakartaEE (Wildfly) Libraries                                                 -->
        <!--*******************************************************************************-->


        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-core</artifactId>
            <version>${version-org.infinispan}</version>
        </dependency>


        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <!-- version managed by BOM: ${version-jakarta.ra-api} -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>

        <!--*******************************************************************************-->
        <!-- JGroups Manipulation Libraries                                                -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.jgroups</groupId>
            <artifactId>jgroups</artifactId>
            <version>${version-org.jgroups-jgroups}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.jgroups.kubernetes</groupId>
            <artifactId>jgroups-kubernetes</artifactId>
            <version>${version-org.jgroups.kubernetes-jgroups-kubernetes}</version>
            <scope>compile</scope>
        </dependency>

        <!--*******************************************************************************-->
        <!-- DRICaTS Libraries                                                 -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-constants</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-jgroups</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-middleware-jgroups</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-middleware-datagrid-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Kafka clients for CentralMessageBroker client -->
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>3.7.0</version>
        </dependency>

        <!--*******************************************************************************-->
        <!-- Apache Commons Libraries                                                      -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>${version-org.apache.commons-lang3}</version>
        </dependency>

        <!--*******************************************************************************-->
        <!-- JSON Manipulation Libraries                                                   -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
            <scope>compile</scope>
        </dependency>

        <!--*******************************************************************************-->
        <!-- Logging (SLF4J) Libraries                                                     -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <scope>compile</scope>
        </dependency>

        <!--*******************************************************************************-->
        <!-- Junit5 (tests)                                                               -->
        <!--*******************************************************************************-->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>
        <!--dependency>
            <groupId>org.jgroups</groupId>
            <artifactId>jgroups</artifactId>
            <version>${version-org.jgroups-jgroups}</version>
            <scope>test</scope>
        </dependency-->
    </dependencies>

</project>
