package net.fhirfactory.dricats.reference.archimate.common.valuesets;

public enum ElementTypeEnum {
    // Application layer
    APPLICATION_COLLABORATION,
    APPLICATION_COMPONENT,
    APPLICATION_DATA_OBJECT,
    APPLICATION_SERVICE,
    APPLICATION_FUNCTION,
    APPLICATION_INTERFACE,
    APPLICATION_PROCESS,
    APPLICATION_INTERACTION,
    APPLICATION_EVENT,

    // Business layer
    BUSINESS_ACTOR,
    BUSINESS_ROLE,
    BUSINESS_COLLABORATION,
    BUSINESS_INTERFACE,
    BUSINESS_PROCESS,
    BUSINESS_FUNCTION,
    BUSINESS_INTERACTION,
    BUSINESS_EVENT,
    BUSINESS_SERVICE,
    BUSINESS_OBJECT,
    CONTRACT,
    REPRESENTATION,
    PRODUCT,
    VALUE,

    // Technology layer
    ARTIFACT,
    COMMUNICATION_NETWORK,
    DEVICE,
    DISTRIBUTION_NETWORK,
    EQUIPMENT,
    FACILITY,
    MATERIAL,
    NODE,
    PATH,
    SYSTEM_SOFTWARE,
    TECHNOLOGY_INTERFACE,
    TECHNOLOGY_COLLABORATION,
    TECHNOLOGY_FUNCTION,
    TECHNOLOGY_INTERACTION,
    TECHNOLOGY_PROCESS,
    TECHNOLOGY_SERVICE
}
