<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.fhirfactory.dricats</groupId>
        <artifactId>dricats-middleware-topologygrid</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>dricats-middleware-topologygrid-central</artifactId>
    <name>DRICaTS :: Middleware :: TopologyGrid :: Central</name>
    <packaging>jar</packaging>

    <dependencies>
        <!--*******************************************************************************-->
        <!-- JakartaEE (Wildfly) Libraries                                                 -->
        <!--*******************************************************************************-->


        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-core</artifactId>
            <version>${version-org.infinispan}</version>
        </dependency>


        <dependency>
            <groupId>jakarta.ws.rs</groupId>
            <artifactId>jakarta.ws.rs-api</artifactId>
            <!-- version managed by BOM: ${version-jakarta.ra-api} -->
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.enterprise</groupId>
            <artifactId>jakarta.enterprise.cdi-api</artifactId>
            <version>4.0.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-middleware-jgroups</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-model-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- OAM common repository interfaces/impls -->
        <dependency>
            <groupId>net.fhirfactory.dricats</groupId>
            <artifactId>dricats-middleware-topologygrid-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Logging -->

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <scope>compile</scope>
        </dependency>

        <!-- Infinispan for distributed cache -->

        <dependency>
            <groupId>org.infinispan</groupId>
            <artifactId>infinispan-core</artifactId>
            <!-- version managed by BOM: ${version-org.infinispan} -->
        </dependency>

        <!--*******************************************************************************-->
        <!-- JGroups Manipulation Libraries                                                -->
        <!--*******************************************************************************-->

        <dependency>
            <groupId>org.jgroups</groupId>
            <artifactId>jgroups</artifactId>
            <version>${version-org.jgroups-jgroups}</version>
            <scope>compile</scope>
        </dependency>

        <!-- H2 database for metrics persistence -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <version>${version-com.h2database-h2}</version>
        </dependency>

        <!-- Jackson for serialising distribution map to JSON strings in JDBC layer -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${version-com.fasterxml.jackson.core-jackson-databind}</version>
        </dependency>

        <!-- Apache Camel for REST exposure -->
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-cdi</artifactId>
            <version>${version-org.apache.camel}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-rest</artifactId>
            <version>${version-org.apache.camel}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-undertow</artifactId>
            <version>${version-org.apache.camel}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-jackson</artifactId>
        </dependency>
    </dependencies>
</project>
